#!/usr/bin/env node

var FILE_ENCODING = 'utf-8',
    EOL = '\n',
    DIST_FILE_PATH = './js/vacation.js';

// setup
var _fs = require('fs');

function concat(fileList, distPath) {
    var out = fileList.map(function(filePath){
            return _fs.readFileSync(filePath, FILE_ENCODING);
        });
    _fs.writeFileSync(distPath, out.join(EOL), FILE_ENCODING);
    console.log(' '+ distPath +' built.');
}

concat([
    "./src/libs/jquery-1.7.2.min.js",
    "./src/app.js",
    "./src/el.js",
    "./src/anchor_actions.js",
    "./src/anchor_count.js",
    "./src/anchor_list.js",
    "./src/countries.js",
    "./src/highlight.js",
    "./src/nearest.js",
    "./src/populate_countries.js",
    "./src/getting_started.js",
    "./src/clicks.js",
    "./src/misses.js",
    "./src/update_info.js",
    "./src/init.js",
    "./src/vacation.js"
], DIST_FILE_PATH);

function uglify(srcPath, distPath) {
    var uglyfyJS = require('uglify-js'),
        jsp = uglyfyJS.parser,
        pro = uglyfyJS.uglify,
        ast = jsp.parse( _fs.readFileSync(srcPath, FILE_ENCODING) );

    ast = pro.ast_mangle(ast);
    ast = pro.ast_squeeze(ast);

    _fs.writeFileSync(distPath, pro.gen_code(ast), FILE_ENCODING);
    console.log(' '+ distPath +' built.');
}

uglify('./js/vacation.js', './js/vacation.min.js');